image: node:9-alpine

variables:
  KUBE_DOMAIN: flat.kubernetes.tobiasz.memleak.pl

stages:
  - test
  - build
  - build-docker
  - review
  - cleanup
  - deploy

lint:
  stage: test
  script:
  - yarn --cache-folder /cache/yarn_cache install
  - yarn run lint

build:
  stage: build
  script:
  - yarn --cache-folder /cache/yarn_cache install
  - yarn run build
  artifacts:
    expire_in: "2 weeks"
    paths:
    - dist/

build-docker-master:
  image: docker:latest
  stage: build-docker
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - master

build-docker:
  image: docker:latest
  stage: build-docker
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

deploy-dev:
  image: registry.gitlab.memleak.pl:443/flat/flat-api/kubectl
  stage: deploy
  script:
    - command scripts/deploy
  environment:
    name: dev
    url: http://dev.$KUBE_DOMAIN
  only:
    - master

review:
  image: registry.gitlab.memleak.pl:443/flat/flat-api/kubectl
  stage: review
  script:
    - command scripts/deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master

stop_review:
  image: registry.gitlab.memleak.pl:443/flat/flat-api/kubectl
  stage: cleanup
  script:
    - command scripts/destroy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    - master
