image: node:9-alpine

cache:
  paths:
  -  node_modules

before_script:
- npm install

stages:
  - test
  - build

lint:
  stage: test
  script:
  -  npm run lint

unit-test:
  stage: test
  script:
  -  npm run unit

build:
  stage: build
  script:
  -  npm run build
  artifacts:
    expire_in: "2 weeks"
    paths:
    - dist/

