#!/usr/bin/env bash

TRACK="${TRACK:-production}"
APP_NAME="${APP_NAME:-flat}"
KUBE_NAMESPACE="${KUBE_NAMESPACE:-flat}"
PIPELINE="${PIPELINE:-manual-$RANDOM}"
BUILD="${BUILD:-manual-$RANDOM}"
IMAGE_VERSION="${IMAGE_VERSION:-master}"
IMAGE_NAME="${IMAGE_NAME:-registry.gitlab.memleak.pl:443/flat/flat-web}"
WEB_NAME="${WEB_NAME:-flat-web-$TRACK}"
WEB_TLS_NAME="${WEB_TLS_NAME:-$WEB_NAME-tls}"

echo "TRACK: $TRACK"
echo "APP_NAME: $APP_NAME"
echo "KUBE_NAMESPACE: $KUBE_NAMESPACE"
echo "PIPELINE: $PIPELINE"
echo "BUILD: $BUILD"
echo "IMAGE_VERSION: $IMAGE_VERSION"
echo "IMAGE_NAME: $IMAGE_NAME"

