#!/usr/bin/env bash

set -e 

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

export DEPLOY_ROOT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source "$DEPLOY_ROOT_DIR/common.bash"

ensure_environment_url
ensure_deploy_variables

CI_ENVIRONMENT_HOSTNAME="${CI_ENVIRONMENT_URL}"
CI_ENVIRONMENT_HOSTNAME="${CI_ENVIRONMENT_HOSTNAME/http:\/\//}"
CI_ENVIRONMENT_HOSTNAME="${CI_ENVIRONMENT_HOSTNAME/https:\/\//}"

TRACK="${CI_ENVIRONMENT_SLUG}"
URL="${CI_ENVIRONMENT_HOSTNAME}"
PIPELINE="${CI_PIPELINE_ID}"
BUILD="${CI_BUILD_ID}"
IMAGE_VERSION="${CI_REGISTRY_TAG}"

echo "Sourcing common variables"
source "$DEPLOY_ROOT_DIR/common_variables"

echo "Running deploy app"
source "$DEPLOY_ROOT_DIR/deploy_app"


echo "Application is accessible at: ${CI_ENVIRONMENT_URL}"
echo ""
