#!/usr/bin/env bash

set -e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

export DEPLOY_ROOT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

unset KUBECONFIG

CI_ENVIRONMENT_HOSTNAME="${CI_ENVIRONMENT_URL}"
CI_ENVIRONMENT_HOSTNAME="${CI_ENVIRONMENT_HOSTNAME/http:\/\//}"
CI_ENVIRONMENT_HOSTNAME="${CI_ENVIRONMENT_HOSTNAME/https:\/\//}"

echo "KUBE_URL: $KUBE_URL"
echo "KUBE_CA_PEM: $KUBE_CA_PEM"
echo "KUBE_TOKEN: $KUBE_TOKEN"

TRACK="production"
KUBE_NAMESPACE="flat-web"
PIPELINE="${CI_PIPELINE_ID}"
BUILD="${CI_BUILD_ID}"
URL="${CI_ENVIRONMENT_HOSTNAME}"
IMAGE_VERSION="master"
REPLICAS="1"

if [ -z "$URL" ]; then echo "Missing URL";  exit 1; fi

echo "Sourcing common variables"
source "$DEPLOY_ROOT_DIR/common_variables"

echo "Running deploy app"
source "$DEPLOY_ROOT_DIR/deploy_app"

echo "Application is accessible at: ${URL}"
echo ""
